### ISSUE TITLE
clear and/or remove example

### ISSUE THREAD

**Issue by bohdanszymanik** [Zaid-Ajaj/Elmish.Toastr#3]
I'm a bit confused about Toastr.clear and Toastr.remove. Since these are unit -> unit I thought these would get executed in the update based on dispatch of a message eg something like

type Message =
...
    | Clear

let update msg model =
    | Clear -> 
        Toastr.clear
         model, Cmd.none

with some button having a Clear msg dispatch on the view

but when I try this I don't clear the displayed Toasts. How do we execute these two functions?

**Comment by Zaid-Ajaj** [comment]
You can just call `Toastr.clear()` like a normal function but I think I should probably put that inside a command

You can test with another toast that have a timeout of 10 seconds

**Comment by Zaid-Ajaj** [comment]
Alright I added commands `Toastr.clearAll` and `Toastr.removeAll` and updated the demo application to use them:
```fs
| ClearAll -> 
    model, Toastr.clearAll 
| RemoveAll ->
    model, Toastr.removeAll
```

**Comment by bohdanszymanik** [comment]
Doh - I just tried with Toastr.remove() and Toastr.clear() and it worked perfect. Having the clearAll/removeAll commands will be great though. Many thanks for this! Let's close the issue. Shall I do it? May as well:)
