### ISSUE TITLE
Add modal dialogs

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Zaid-Ajaj/Elmish.Toastr#6]
It'd be great to have also the possibility of creating modal dialogs as Elmish commands, maybe here or in a different package.

**Comment by Zaid-Ajaj** [comment]
Hello Alfonso, I don't think toastr has modal dialogs but you probably want something like [Elmish.SweetAlert](https://github.com/Zaid-Ajaj/Elmish.SweetAlert) which has all the modal dialogs you want, implemented as Elmish commands :)

**Comment by alfonsogarciacaro** [comment]
Oh, forgot about that one, thank you! You made my day 😍

**Comment by Zaid-Ajaj** [comment]
Happy to help Alfonso! :smile:
